- name: Install pycurl package in order to use the apt_repository module
  apt: pkg=python-pycurl state=present
  sudo: yes


- name: NodeJS | Add PPA key
  command: "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68576280"
  become: yes
  become_user: root

- name: NodeJS | Add PPA
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
  become: yes
  become_user: root

- name: NodeJS | Install package
  apt:
    name: nodejs
  become: yes
  become_user: root

- name: Install system package dependencies
  apt: name={{ item }} state=present update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - git
    - python2.7-dev
    - libffi-dev
    - libjpeg-dev
    - zlib1g-dev
    - python-pip
    - nodejs
    - postfix
    - apt-transport-https
    - ca-certificates
    - mongodb-org
    - vim
    - python-dev
    - memcached
    - libmemcached-dev
    - libxslt1-dev
    - apparmor
    - pandoc
    - pandoc-citeproc

- name: Install node-gyp
  shell: "npm install -g node-gyp-install && /usr/lib/node_modules/node-gyp-install/bin.js"
  become: yes

- name: Clone ctk-cli
  git:
    repo: git://github.com/cdeepakroy/ctk-cli.git
    dest: "{{ root_dir }}/ctk-cli"
    accept_hostkey: yes

- name: Clone girder
  git:
    repo: git://github.com/girder/girder.git
    dest: "{{ girder_root }}"
    accept_hostkey: yes
    version: "{{ girder_version }}"

- name: Clone slicer_cli_web plugin
  git:
    repo: git://github.com/girder/slicer_cli_web.git
    dest: "{{ root_dir }}/slicer_cli_web"
    accept_hostkey: yes
    version: "{{ slicer_cli_web_version }}"

- name: Clone HistomicsTK
  git:
    repo: git://github.com/DigitalSlideArchive/HistomicsTK.git
    dest: "{{ root_dir }}/HistomicsTK"
    accept_hostkey: yes
    version: "{{ histomicstk_version }}"

- name: Clone large_image plugin
  git:
    repo: git://github.com/DigitalSlideArchive/large_image.git
    dest: "{{ root_dir }}/large_image"
    accept_hostkey: yes
    version: "{{ large_image_version }}"

- name: Clone DSA plugin
  git:
    repo: git://github.com/DigitalSlideArchive/digital_slide_archive.git
    dest: "{{ root_dir }}/digital_slide_archive"
    accept_hostkey: yes
    version: "{{ dsa_version }}"

- name: Get the most recent version of pip
  pip: name=pip extra_args="-U"
  sudo: yes

- name: Install requests (needed to resolve conflict with docker-py)
  pip: name=requests version=2.10.0
  sudo: yes

- name: Install ctk-cli using pip
  pip:
    name: "{{ root_dir }}/ctk-cli"
    extra_args: "-e"
    state: present
  sudo: yes


- name: Create directory for build
  file: state=directory path="{{ root_dir }}/girder/clients/web/static/built"

- name: Download fontello.zip
  command: wget -O fontello.zip https://data.kitware.com/api/v1/file/57c5d1fc8d777f10f269dece/download
  args:
    chdir: "{{ root_dir }}/girder/clients/web/static/built"

- name: Install girder using pip
  pip:
    name: "{{ girder_root }}[worker]"
    extra_args: "-e"
    state: present
  sudo: yes

- name: Install numpy (must be installed before large_image plugin)
  pip: name=numpy version=1.11.2
  sudo: yes

- name: Install python libtiff from git
  pip: name='git+https://github.com/pearu/pylibtiff@848785a6a9a4e2c6eb6f56ca9f7e8f6b32e523d5' extra_args='--force-reinstall --ignore-installed --upgrade' editable=False
  sudo: yes

- name: Install our external girder plugins
  command: girder-install plugin -s {{ root_dir }}/slicer_cli_web {{ root_dir }}/large_image {{ root_dir }}/HistomicsTK {{ root_dir }}/digital_slide_archive
  environment:
    GIRDER_LOCAL_FONTELLO_ARCHIVE: "{{ root_dir }}/girder/clients/web/static/built/fontello.zip"
  sudo: yes

- name: Install girder-client pip package
  pip: name=girder-client version=1.3.1
  sudo: yes

- name: Install HistomicsTK pypi C requirements
  pip: requirements="{{ girder_root }}/plugins/HistomicsTK/requirements_c.txt"
  sudo: yes

- name: Set the girder configuration file
  template: src=girder.local.cfg.j2 dest={{ girder_root }}/girder/conf/girder.local.cfg

- name: Install girder as a service
  template: src=girder.conf.j2 dest=/etc/init/girder.conf mode=644 owner=root
  sudo: yes

- name: Start girder as a service
  service: name=girder state=restarted enabled=yes
  sudo: yes

- name: Wait for girder startup
  wait_for:
    port: "{{ girder_socket_port }}"
    delay: 1

- name: Ensure girder admin user exists
  girder:
    port: "{{ girder_socket_port }}"
    user:
      firstName: admin
      lastName: admin
      password: "{{ girder_admin_password }}"
      login: "{{ girder_admin_user }}"
      email: "{{ girder_admin_email }}"
      admin: yes
    state: present

- name: Ensure worker user exists
  girder:
    port: "{{ girder_socket_port }}"
    user:
      firstName: Worker
      lastName: Robot
      password: "{{ girder_celery_password }}"
      login: "{{ girder_celery_user }}"
      email: "{{ girder_celery_email }}"
    state: present

- name: Ensure required plugins are enabled
  girder:
    port: "{{ girder_socket_port }}"
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    plugins: "{{ girder_plugins }}"
    state: present

- name: Restart girder as a service to make sure our plugins are running
  service: name=girder state=restarted enabled=yes
  sudo: yes

- name: Wait for girder startup
  wait_for:
    port: "{{ girder_socket_port }}"
    delay: 1

- name: Set worker broker setting
  girder:
    port: "{{ girder_socket_port }}"
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    put:
      path: system/setting
      parameters:
        key: worker.broker
        value: "amqp://guest@{{ mq_private_ip }}//"

- name: Set worker backend setting
  girder:
    port: "{{ girder_socket_port }}"
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    put:
      path: system/setting
      parameters:
        key: worker.backend
        value: "amqp://guest@{{ mq_private_ip }}//"

- name: Set homepage markdown setting
  girder:
    port: "{{ girder_socket_port }}"
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    put:
      path: system/setting
      parameters:
        key: homepage.markdown
        value: |
          # Digital Slide Archive
          ---
          ## Bioinformatics Platform

          Welcome to the **Digital Slide Archive**!

          Developers who want to use the Girder REST API should check out the [interactive web API docs](/api/v1).

          The [HistomicsTK](/histomicstk) application is enabled.

- name: Ensure the existence of the filesystem assetstore
  girder:
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_socket_port }}"
    assetstore:
      name: default
      type: filesystem
      root: "{{ root_dir }}/assetstore"
      current: true
    state: present

- name: Get assetstore list
  girder:
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_socket_port }}"
    get:
      path: "/assetstore"
  register: assetstore_list

- name: Ensure the existence of the TCGA collection
  girder:
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_socket_port }}"
    collection:
      name: TCGA
      public: yes
    state: present
  register: tcga_collection
  tags: data_import

- name: Ensure the existence of the sample images folder
  girder:
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_socket_port }}"
    folder:
      parentType: collection
      parentId: "{{ tcga_collection['gc_return']['_id'] }}"
      name: "Sample Images"
      public: yes
    state: present
  register: sample_images_folder
  tags: data_import

- name: Import sample images into filesystem assetstore
  girder:
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_socket_port }}"
    post:
      path: "assetstore/{{ assetstore_list['gc_return'][0]['_id'] }}/import"
      parameters:
        importPath: /vagrant/sample_images
        destinationType: folder
        destinationId: "{{ sample_images_folder['gc_return']['_id'] }}"
        fileExcludeRegex: "\\.gitignore"
  when: vagrant is defined
  tags: data_import
