---
- name: Ensure the girder group exists
  group: name="{{ girder_exec_group }}" state=present
  become: true

- name: Ensure the girder user exists
  user: shell=/bin/bash
        name="{{ girder_exec_user }}"
        groups="{{ girder_exec_group }}"
        append=yes
  become: true

- name: Give ownership of root dir to appropriate user
  file:
    path: "{{ root_dir }}"
    owner: "{{ girder_exec_user }}"
    group: "{{ girder_exec_group }}"
    mode: 0775
    state: directory
    recurse: no
  become: true

- name: Install curl
  apt: pkg=curl state=installed
  become: true

- name: Install aptitude
  apt: pkg=aptitude state=installed
  become: true
  when: (vagrant is defined) or (docker is defined)

- name: Upgrade system packages
  apt: 
    upgrade: safe
    force: yes
    update_cache: yes
  become: true
  when: (vagrant is defined) or (docker is defined)

- name: Create a docker group
  group:
    gid: 998
    name: docker
    state: present
  become: true
  when: docker is defined

- name: Join the docker group
  user:
    name: ubuntu
    append: yes
    groups: docker
    state: present
  become: true
  when: docker is defined
