---
- hosts: local
  roles:
    - role: common
      tags: common
      when:
        - docker is defined
        - docker != "provision"
    - role: openslide
      tags: openslide
      when:
        - docker is defined
        - docker != "provision"
    - role: worker
      tags: worker
      when:
        - docker is defined
        - docker == "girder_worker"
    - role: girder.girder
      girder_path: "{{ root_dir }}/girder"
      girder_version: "master"
      girder_web: no
      girder_daemonize: no
      become: true
      become_user: "{{ girder_exec_user }}"
      tags: girder
      when:
        - docker is defined
        - docker == "histomicstk"

    - role: girder-histomicstk
      tags: girder
      when:
        - docker  is defined
        - docker == "histomicstk"

    - role: provision
      tags: provision
      when:
        - docker is defined
        - docker == "provision"
    # - role: itk
    #   tags: itk
    #   when: docker is undefined
  vars:
    root_dir: /opt/histomicstk
    girder_admin_user: admin
    girder_admin_email: histomicstk.admin@kitware.com
    girder_admin_password: password
    girder_socket_port: 8080
    girder_socket_scheme: http
    girder_exec_user: ubuntu
    girder_exec_group: ubuntu
    enabled_girder_plugins:
      - digital_slide_archive
      - HistomicsTK
      - homepage
      - xtk_demo
    girder_celery_user: worker-robot
    girder_celery_email: histomicstk.celery@kitware.com
    girder_celery_password: celery
    girder_root: "{{ root_dir }}/girder"
    worker_exec_user: ubuntu
    worker_exec_group: ubuntu
    mongo_private_ip: mongodb
    girder_api_url: http://histomicstk:8080/api/v1
    mongo_girder_database: girder
    mq_private_ip: rmq
    memcached_url: dockerhost

