---
- name: Fetch GPG key for docker package
  sudo: yes
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker PPA
  sudo: yes
  shell: echo "deb https://apt.dockerproject.org/repo ubuntu-`lsb_release -c -s` main"  | sudo tee /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list


- name: Install worker dependencies
  sudo: yes
  apt: update-cache=yes name={{ item }} state=present
  with_items:
    - libffi-dev
    - libssl-dev
    - python-pip
    - python-dev
    - git
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libpng-dev
    - docker-engine

- name: Start docker daemon
  service: name=docker state=started enabled=yes
  sudo: yes

- name: Clone girder_worker
  sudo: yes
  git:
      repo: git://github.com/girder/girder_worker.git
      dest: /opt/girder_worker
      accept_hostkey: yes
      force: yes
      version: "{{ girder_worker_version }}"

- name: Create local worker config file
  sudo: yes
  template:
    src: worker.local.cfg.j2
    dest: /opt/girder_worker/girder_worker/worker.local.cfg
    mode: 0644
    owner: "{{ worker_exec_user }}"
    group: "{{ worker_exec_group }}"

- name: Install girder_worker
  sudo: yes
  pip:
    name: /opt/girder_worker[docker,girder_io]
    extra_args: "-e"
    state: present


- name: Change ownership of worker to correct user
  sudo: yes
  file:
    dest: /opt/girder_worker
    owner: "{{worker_exec_user}}"
    group: "{{worker_exec_group}}"
    state: directory
    recurse: yes

- name: Create docker group
  group: name=docker state=present

- name: Add worker user to docker group
  user: shell=/bin/bash
        name={{ worker_exec_user }}
        groups=docker
        append=yes
  sudo: yes

- name: Restart docker daemon
  service: name=docker state=restarted enabled=yes
  sudo: yes

- name: Install girder worker as a service
  template:
      src: girder_worker.conf
      dest: /etc/init/girder_worker.conf
      mode: 644
      owner: root
  sudo: yes

- name: Restart worker as a service
  service: name=girder_worker state=restarted enabled=yes
  sudo: yes
